version: "3.8"

volumes:
  database:
    driver: local

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nextauth
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: root
    volumes:
      - database:/var/lib/postgres
